name: Deploy Yolo

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          script: |
            cd ~/nadinePolyAI
            git fetch origin
            git checkout dev
            git pull origin dev
            sudo systemctl restart yolo
            sleep 5
            curl -f http://localhost:8081/predictions/score/0

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Prod
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          script: |
            cd ~/nadinePolyAI
            git fetch origin
            git checkout main
            git pull origin main
            sudo systemctl restart yolo
            sleep 5
            curl -f http://localhost:8081/predictions/score/0
